name = "track-worker"
main = "src/index.ts"
compatibility_date = "2024-03-18"
# node_compat = true
kv_namespaces = [
  { binding = "TOKEN", id = "dbb1594c25a14e23a8f4a6ba5548a012", preview_id = "e8d30db3dc2f4bbc8c5852b96317fd68" }
]

[placement]
mode = "smart"

[site]
bucket = "./dist"

# Keep vars last for easy insertion
# must have newline
[vars]
SENTRY_DSN="https://034ae5af15fc670bbe881b6affe5f64a@o54215.ingest.us.sentry.io/4506986928078848"
SPOTIFY_CLIENT_ID="4fb6547712a1470fba276e0adb4274a4"
