name = "scrdb-worker"
main = "src/index.ts"
compatibility_date = "2023-12-01"
# node_compat = true

[placement]
mode = "smart"

[site]
bucket = "./dist"

# Keep vars last for easy insertion
# must have newline
[vars]
SENTRY_DSN="https://222be3dbbb11464fa3d68ac2af81c100@o54215.ingest.sentry.io/4505438514380800"
